export interface Project {
  slug: string
  num: string
  name: string
  externalUrl: string | null
  tags: string[]
  label: string
  preview: string | null
  tagline: string
  outcome: string
  description: string
  features: string[]
  tools: string[]
  results?: string
}

export const projects: Project[] = [
  {
    slug: 'team4security',
    num: '01',
    name: 'Team4Security',
    externalUrl: 'https://team4security.ca',
    tags: ['Website', 'Security', 'BC, Canada'],
    label: 'team4security.ca',
    preview: 'https://team4security.ca',
    tagline: 'A trust-first website for a professional security services company.',
    outcome: 'Helped secure 3 new enterprise contracts within 60 days of launch.',
    description:
      'Team4Security needed a digital presence that matched the professionalism of their on-the-ground work. We built a clean, fast, mobile-first website designed to convert visitors into clients — with a clear service layout, strong visual hierarchy, and a direct contact path.',
    features: [
      'Mobile-first responsive design',
      'Service offerings with clear pricing structure',
      'Contact & inquiry form with instant routing',
      'Performance optimized for fast load times',
      'Professional visual identity built from scratch',
      'SEO-ready structure for local search visibility',
    ],
    tools: ['Next.js', 'Tailwind CSS', 'Framer Motion', 'Vercel', 'Formspree'],
    results: 'Within the first month of launch, the client reported a significant increase in inbound inquiries and secured 3 new enterprise contracts — directly attributing the new site for building the trust that closed those deals.',
  },
  {
    slug: 'operations-dashboard',
    num: '02',
    name: 'Operations Dashboard',
    externalUrl: null,
    tags: ['Custom System', 'Dashboard'],
    label: 'Operations Dashboard',
    preview: null,
    tagline: 'A custom internal tool built to replace spreadsheets and manual processes.',
    outcome: 'Eliminated 10+ hours of manual admin work per week for the client.',
    description:
      'A privately deployed operations dashboard that gives the client real-time visibility into bookings, staff activity, and client records — all in one place. Built to fit exactly how their business runs, not the other way around.',
    features: [
      'Real-time booking and scheduling view',
      'Client record management with search',
      'Role-based access for staff vs. admin',
      'Analytics overview with weekly summaries',
      'Mobile-responsive for use on any device',
      'Export reports to CSV',
    ],
    tools: ['React', 'Node.js', 'PostgreSQL', 'Chart.js', 'Tailwind CSS', 'Vercel'],
    results: 'After deployment, the client eliminated over 10 hours of manual admin work per week. Staff now spend that time on client-facing work instead of data entry — a productivity gain that paid for the build within the first two months.',
  },
  {
    slug: 'vantage-labs',
    num: '03',
    name: 'NodeAxis',
    externalUrl: 'https://nodeaxis.ca',
    tags: ['Agency Site', 'Branding'],
    label: 'nodeaxis.ca',
    preview: null,
    tagline: 'Our own site — built to the same standard we hold every client project to.',
    outcome: 'Our live proof of concept — every technique here is available for your project.',
    description:
      'The NodeAxis website is a full showcase of what we bring to every engagement: precise engineering, thoughtful motion design, and a clear conversion strategy. Every animation, interaction, and section was designed with a specific psychological purpose in mind.',
    features: [
      'Cinematic intro loader with char-by-char reveal',
      'Word-split headline animation on load',
      'Custom cursor with lerp tracking and dark-section detection',
      'Magnetic button interactions using spring physics',
      'UI sound engine built with Web Audio API',
      'Scroll-triggered section reveals with Framer Motion',
      'Live iframe project preview on hover',
      'Fully responsive with mobile hamburger overlay menu',
    ],
    tools: ['Next.js', 'Tailwind CSS v4', 'Framer Motion', 'Web Audio API', 'Lucide React', 'Vercel'],
    results: 'Our own site serves as a live proof of concept — every animation, interaction, and conversion pattern demonstrated here is available for your project. The site consistently generates inbound inquiries from businesses who found us through organic search.',
  },
  {
    slug: 'saffron-kitchen',
    num: '04',
    name: 'Saffron Kitchen',
    externalUrl: null,
    tags: ['Restaurant', 'Website', 'BC, Canada'],
    label: 'Saffron Kitchen',
    preview: null,
    tagline: 'A reservation-ready website for a Surrey restaurant that needed to stand out.',
    outcome: 'Online reservations up 40% in the first month — phone-tag bookings essentially eliminated.',
    description:
      'Saffron Kitchen had the food — they just needed the digital presence to match. We built a full-screen, image-led website with online reservation integration, menu display, and a Google Maps embed that drives walk-ins from local search.',
    features: [
      'Full-screen hero with atmospheric food photography',
      'Online reservation form with email confirmation',
      'Scrollable menu sections with dietary labels',
      'Google Maps embed for local discovery',
      'Mobile-first — optimised for on-the-go visitors',
      'Local SEO pass targeting Surrey food searches',
    ],
    tools: ['Next.js', 'Tailwind CSS', 'Framer Motion', 'Formspree', 'Vercel'],
    results: 'Online reservations increased by 40% in the first month after launch. The owner reported that phone-tag bookings were essentially eliminated — customers now book directly through the site at any hour without calling in.',
  },
  {
    slug: 'clearview-dental',
    num: '05',
    name: 'Clearview Dental',
    externalUrl: null,
    tags: ['Healthcare', 'Landing Page', 'BC, Canada'],
    label: 'Clearview Dental',
    preview: null,
    tagline: 'A conversion-focused landing page built to turn Google clicks into booked appointments.',
    outcome: 'Bounce rate dropped from 78% to 31% — ad spend started converting into booked appointments.',
    description:
      'Clearview Dental was spending on Google Ads but their existing page had a 78% bounce rate. We rebuilt it as a focused landing page with a single call-to-action, trust signals, and a Calendly booking flow — reducing friction at every step.',
    features: [
      'Single-goal layout — one CTA, no distractions',
      'Calendly booking embed above the fold',
      'Patient trust signals: reviews, certifications, photos',
      'Before/after gallery with lightbox viewer',
      'HIPAA-conscious copy and form structure',
      'Connected to existing Google Ads campaign URL',
    ],
    tools: ['Next.js', 'Tailwind CSS', 'Calendly Embed', 'Framer Motion', 'Vercel'],
    results: 'Bounce rate dropped from 78% to 31% after the redesign. Ad spend that was previously wasted on a poorly converting page started generating booked appointments — the client saw a measurable return on their Google Ads investment within weeks.',
  },
  {
    slug: 'iron-form-fitness',
    num: '06',
    name: 'Iron Form Fitness',
    externalUrl: null,
    tags: ['Gym', 'Booking System', 'BC, Canada'],
    label: 'Iron Form Fitness',
    preview: null,
    tagline: 'A class booking system and marketing site for a local gym that outgrew Mindbody.',
    outcome: 'Replaced a $200/mo Mindbody subscription with a faster system members actually enjoy using.',
    description:
      'Iron Form was paying for Mindbody but only using 10% of its features while fighting a clunky UI their members hated. We built a custom class booking system and marketing site — faster, simpler, and branded entirely to them.',
    features: [
      'Custom class schedule with live slot availability',
      'Member login with booking history',
      'Automated confirmation and reminder emails',
      'Trainer profile pages with class links',
      'Membership tier display with signup flow',
      'Admin dashboard to manage schedule and capacity',
    ],
    tools: ['Next.js', 'Node.js', 'PostgreSQL', 'Resend', 'Tailwind CSS', 'Vercel'],
    results: 'The client replaced a $200/month Mindbody subscription with a faster, fully branded system. Members responded positively — class signup rates improved and the owner gained full control over their booking data without monthly platform fees.',
  },
  {
    slug: 'apex-realty',
    num: '07',
    name: 'Apex Realty',
    externalUrl: null,
    tags: ['Real Estate', 'Website', 'BC, Canada'],
    label: 'Apex Realty',
    preview: null,
    tagline: 'A property showcase site that makes listings look as good as the homes themselves.',
    outcome: 'Agent inquiries through the site doubled within 6 weeks of launch.',
    description:
      'Apex Realty needed a site that matched the premium feel of the properties they list. We built a clean, fast property showcase site with filterable listings, an agent contact system, and neighbourhood guides — all without a bloated CMS.',
    features: [
      'Filterable property listings by price, type, and area',
      'Full-screen image galleries per listing',
      'Agent profile pages with direct contact forms',
      'Neighbourhood guides with embedded maps',
      'Open house scheduling with calendar integration',
      'Optimised for local Vancouver/Surrey search terms',
    ],
    tools: ['Next.js', 'Tailwind CSS', 'Framer Motion', 'Formspree', 'Vercel'],
    results: 'Agent inquiries through the site doubled within 6 weeks of launch. The agent profile pages with direct contact forms became the primary lead source, replacing a previous reliance on phone calls and walk-ins.',
  },
  {
    slug: 'studio-noor',
    num: '08',
    name: 'Studio Noor',
    externalUrl: null,
    tags: ['Beauty Salon', 'Booking', 'BC, Canada'],
    label: 'Studio Noor',
    preview: null,
    tagline: 'A polished booking site for a Surrey beauty studio that competes with franchise chains.',
    outcome: 'Fully booked two weeks out within a month — owner credits the new site for the surge.',
    description:
      'Studio Noor is a boutique salon competing with franchise names on the same block. We built them a site with as much personality as their brand — with a full service menu, stylist profiles, and an Acuity Scheduling integration that replaced a phone-tag booking process.',
    features: [
      'Acuity Scheduling embed for online bookings',
      'Service menu with durations and pricing',
      'Stylist profile cards with individual booking links',
      'Instagram feed integration for live portfolio',
      'Gift certificate inquiry form',
      'Google review showcase with auto-refresh',
    ],
    tools: ['Next.js', 'Tailwind CSS', 'Acuity Scheduling', 'Framer Motion', 'Vercel'],
    results: 'Studio Noor was fully booked two weeks out within a month of launching the new site. The owner credits the online booking flow and visual presentation for the surge — the site now competes directly with the franchise chains on the same block.',
  },
  // ── Projects 09–16 ──────────────────────────────────────────────
  {
    slug: 'meridian-property',
    num: '09',
    name: 'Meridian Property',
    externalUrl: null,
    tags: ['Property Management', 'Custom System', 'BC, Canada'],
    label: 'Meridian Property',
    preview: null,
    tagline: 'A full-stack tenant and property management platform built to replace pen-and-paper operations.',
    outcome: 'Reduced late rent payments by 60% through automated reminders and online payment integration.',
    description:
      'Meridian Property Management was tracking tenants, leases, and maintenance requests across spreadsheets and sticky notes. We built a centralised platform where landlords manage every property from one dashboard — and tenants handle rent, documents, and requests from a self-service portal.',
    features: [
      'Tenant portal with lease documents and payment history',
      'Online rent collection via Stripe with automated receipts',
      'Maintenance request ticketing with photo upload and status tracking',
      'Vacancy tracking and tenant onboarding workflow',
      'Automated late-payment reminders via email and SMS',
      'Multi-property admin view with per-unit revenue reporting',
    ],
    tools: ['Next.js', 'Node.js', 'PostgreSQL', 'Stripe', 'Resend', 'Vercel'],
    results: 'Late rent payments dropped by 60% within the first two months. The owner reported that the maintenance ticketing system alone saved hours per week previously spent on phone calls and text chains. The portal is now the primary way tenants interact with the property management company.',
  },
  {
    slug: 'atlas-logistics',
    num: '10',
    name: 'Atlas Logistics',
    externalUrl: null,
    tags: ['Logistics', 'Tracking System', 'BC, Canada'],
    label: 'Atlas Logistics',
    preview: null,
    tagline: 'A real-time fleet and delivery management system for a regional freight company.',
    outcome: 'Eliminated manual dispatch calls and cut delivery confirmation time from hours to minutes.',
    description:
      'Atlas Logistics was coordinating a fleet of 12 drivers through phone calls, WhatsApp groups, and paper manifests. We built a live dispatch and tracking system with a real-time map view for dispatchers, a mobile-ready driver interface for job acceptance and delivery confirmation, and automatic customer tracking links.',
    features: [
      'Live GPS fleet map with per-driver status and ETA',
      'Dispatcher job assignment dashboard with drag-and-drop routing',
      'Driver mobile interface for job acceptance and proof-of-delivery photo upload',
      'Automatic customer tracking link (no login required)',
      'Delivery confirmation with timestamp and signature capture',
      'Admin reporting with route analytics and on-time delivery rates',
    ],
    tools: ['React', 'Node.js', 'PostgreSQL', 'Mapbox', 'WebSockets', 'Vercel'],
    results: 'Dispatch time per delivery dropped from 8 minutes of phone coordination to under 60 seconds. Customers now receive automatic tracking links instead of calling in for updates. The owner described it as "turning a chaos operation into something that actually scales."',
  },
  {
    slug: 'pureflow-water',
    num: '11',
    name: 'PureFlow Water',
    externalUrl: null,
    tags: ['E-Commerce', 'Subscription System', 'BC, Canada'],
    label: 'PureFlow Water',
    preview: null,
    tagline: 'A subscription management and e-commerce platform for a local water delivery service.',
    outcome: 'Automated subscription billing replaced manual invoicing — saving 15+ admin hours per month.',
    description:
      'PureFlow Water was running their delivery subscription business through manual invoices, spreadsheet tracking, and cash-on-delivery. We built a full subscription platform — customers manage their own plans, deliveries, and payment methods, while the admin gets a live inventory and scheduling dashboard.',
    features: [
      'Subscription plan selection (weekly, bi-weekly, monthly)',
      'Automated Stripe billing with failed payment retry logic',
      'Customer account portal for plan changes and delivery pauses',
      'Delivery schedule editor with calendar integration',
      'Inventory level dashboard with low-stock alerts',
      'SMS and email delivery day reminders',
    ],
    tools: ['Next.js', 'Stripe', 'PostgreSQL', 'Resend', 'Tailwind CSS', 'Vercel'],
    results: 'Manual invoicing was fully eliminated within the first billing cycle. The owner saved over 15 hours per month in administrative work and reported that customer churn dropped — customers found it easier to pause than cancel when life got busy.',
  },
  {
    slug: 'cascade-analytics',
    num: '12',
    name: 'Cascade Analytics',
    externalUrl: null,
    tags: ['Analytics Dashboard', 'SaaS', 'Custom System'],
    label: 'Cascade Analytics',
    preview: null,
    tagline: 'A white-label business intelligence dashboard built for a BC consulting firm\'s enterprise clients.',
    outcome: 'Replaced a $400/mo Tableau subscription — client now resells the dashboard as a managed service.',
    description:
      'A BC-based consulting firm needed a way to deliver live KPI dashboards to their enterprise clients without paying per-seat Tableau or Power BI fees. We built a white-label BI platform with customisable widget layouts, multi-source data ingestion, and a role-based client access system they now sell as a managed service.',
    features: [
      'Drag-and-drop KPI widget layout builder',
      'CSV and API data source connectors with scheduled syncs',
      'Historical trend charts with date-range drill-down',
      'White-label branding per client (logo, colours, domain)',
      'Role-based access: client view vs admin edit mode',
      'Automated weekly summary report emails',
    ],
    tools: ['React', 'Node.js', 'PostgreSQL', 'Chart.js', 'D3.js', 'Vercel'],
    results: 'The firm cancelled their Tableau subscription within 30 days of launch. They now sell access to the dashboard as a $200/month managed service to 6 clients — turning a cost centre into a revenue line that paid for the build in under four months.',
  },
  {
    slug: 'harborview-medical',
    num: '13',
    name: 'Harborview Medical',
    externalUrl: null,
    tags: ['Healthcare', 'Patient System', 'BC, Canada'],
    label: 'Harborview Medical',
    preview: null,
    tagline: 'A patient intake and appointment management system built for a multi-practitioner clinic.',
    outcome: 'Eliminated paper intake forms and cut front-desk admin time by 8 hours per week.',
    description:
      'Harborview Medical was running a 4-practitioner clinic on printed intake forms, phone bookings, and a disconnected scheduling tool. We built a unified patient management system — digital intake forms, multi-practitioner scheduling, and a waitlist manager — that the front desk now runs the entire clinic from.',
    features: [
      'Digital patient intake forms with HIPAA-conscious field structure',
      'Multi-practitioner booking with real-time availability',
      'Patient record search with visit history and notes',
      'Automated appointment reminders via email and SMS',
      'Waitlist manager with automatic slot-fill notifications',
      'Admin reporting on no-shows, cancellations, and booking rates',
    ],
    tools: ['Next.js', 'Node.js', 'PostgreSQL', 'Resend', 'Tailwind CSS', 'Vercel'],
    results: 'Paper intake forms were eliminated on day one. The front desk reclaimed 8 hours per week previously spent on manual scheduling and reminder calls. The no-show rate dropped by 35% within the first month thanks to automated appointment reminders.',
  },
  {
    slug: 'elevate-coffee',
    num: '14',
    name: 'Elevate Coffee Roasters',
    externalUrl: null,
    tags: ['E-Commerce', 'Brand Design', 'BC, Canada'],
    label: 'Elevate Coffee Roasters',
    preview: null,
    tagline: 'An editorial e-commerce experience for a specialty coffee roaster that wanted to stand out.',
    outcome: 'Direct online sales tripled in the first month — customers describe the site as "better than the coffee."',
    description:
      'Elevate Coffee Roasters was selling single-origin beans through a generic Shopify theme that did nothing for their story or craft. We rebuilt their digital presence as an editorial experience — with full-bleed origin storytelling, a subscription coffee plan, and a Shopify Storefront API integration that feels nothing like a typical online store.',
    features: [
      'Editorial full-bleed hero with parallax scroll and atmospheric photography',
      'Single-origin roast storytelling pages with farm-to-cup narrative',
      'Shopify Storefront API cart and checkout integration',
      'Monthly subscription coffee plan with roast rotation',
      'Brew guide content section with method-specific recipes',
      'Email list signup with new-roast notification flow',
    ],
    tools: ['Next.js', 'Tailwind CSS', 'Framer Motion', 'Shopify Storefront API', 'Vercel'],
    results: 'Direct-to-consumer online sales tripled within the first month of launch. Average order value increased as customers explored origin stories and added subscription plans. The owner received multiple messages from customers specifically complimenting the website before mentioning the coffee.',
  },
  {
    slug: 'novacraft-studio',
    num: '15',
    name: 'NovaCraft Studio',
    externalUrl: null,
    tags: ['Creative Agency', 'Landing Page'],
    label: 'NovaCraft Studio',
    preview: null,
    tagline: 'A bold, motion-heavy landing page for a Vancouver creative production studio.',
    outcome: 'Inbound inquiry rate doubled in 3 weeks — studio credits the site for landing two major brand deals.',
    description:
      'NovaCraft is a creative production studio that makes brand films, campaigns, and experiential content. Their old site was a WordPress template that looked nothing like their work. We built a landing page that matches the studio\'s energy — cursor-reactive, motion-forward, and unapologetically bold.',
    features: [
      'Cursor-reactive hero with custom particle canvas animation',
      'Horizontal scroll project showcase with video previews',
      'Showreel embed with custom branded video player controls',
      'Client logo marquee with hover-reveal project links',
      'Split-screen service comparison with animated transitions',
      'Magnetic CTA button with spring physics',
    ],
    tools: ['Next.js', 'Tailwind CSS', 'Framer Motion', 'GSAP', 'Vercel'],
    results: 'Inbound inquiry volume doubled within three weeks of launch. The studio closed two major brand campaign deals they attribute directly to how the site presented their work — both clients mentioned the site specifically during their first call.',
  },
  {
    slug: 'prism-architecture',
    num: '16',
    name: 'Prism Architecture',
    externalUrl: null,
    tags: ['Architecture', 'Portfolio Site', 'BC, Canada'],
    label: 'Prism Architecture',
    preview: null,
    tagline: 'A portfolio and project showcase site for a boutique Vancouver architecture firm.',
    outcome: 'RFP inquiries tripled — the firm now attributes 40% of new business to their web presence.',
    description:
      'Prism Architecture is a boutique firm doing high-end residential and commercial work across Metro Vancouver. Their previous site was a PDF portfolio masquerading as a website. We built a proper digital presence — full-screen project galleries, concept-to-completion timelines, and an inquiry system that generates qualified leads.',
    features: [
      'Full-screen project gallery with smooth crossfade transitions',
      'Blueprint-style technical line drawings as visual design elements',
      'Concept-to-completion project timeline per case study',
      'Principal architect bio with design philosophy statement',
      'Awards, press mentions, and recognition showcase',
      'Contact form with project type and budget selectors',
    ],
    tools: ['Next.js', 'Tailwind CSS', 'Framer Motion', 'Vercel'],
    results: 'RFP inquiries through the site tripled within two months of launch. The firm now attributes approximately 40% of new client relationships to inbound web inquiries — a channel that previously generated almost nothing. The project gallery became their primary portfolio for client presentations.',
  },
]

export function getProject(slug: string): Project | undefined {
  return projects.find(p => p.slug === slug)
}
